/* Generated By:JavaCC: Do not edit this line. FSMParserConstants.java */
package logicrepository.plugins.fsm.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FSMParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int ARROW = 2;
  /** RegularExpression Id. */
  int LBRACE = 3;
  /** RegularExpression Id. */
  int RBRACE = 4;
  /** RegularExpression Id. */
  int EQUAL = 5;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int ALIAS = 7;
  /** RegularExpression Id. */
  int FAIL = 8;
  /** RegularExpression Id. */
  int DEF = 9;
  /** RegularExpression Id. */
  int ID = 10;
  /** RegularExpression Id. */
  int DIGIT = 11;
  /** RegularExpression Id. */
  int LETTER = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "\"->\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\",\"",
    "\"alias\"",
    "\"fail\"",
    "\"default\"",
    "<ID>",
    "<DIGIT>",
    "<LETTER>",
  };

}
