/* Generated By:JavaCC: Do not edit this line. CFGParserConstants.java */
package javamop.logicpluginshells.javacfg.cfgutil;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CFGParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int ALT = 2;
  /** RegularExpression Id. */
  int EPSILON = 3;
  /** RegularExpression Id. */
  int COMMA = 4;
  /** RegularExpression Id. */
  int SYMBOL = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int LETTER = 7;
  /** RegularExpression Id. */
  int ARROW = 8;
  /** RegularExpression Id. */
  int PLUS = 9;
  /** RegularExpression Id. */
  int STAR = 10;
  /** RegularExpression Id. */
  int LPAREN = 11;
  /** RegularExpression Id. */
  int RPAREN = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "\"|\"",
    "\"epsilon\"",
    "\",\"",
    "<SYMBOL>",
    "<DIGIT>",
    "<LETTER>",
    "\"->\"",
    "\"+\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
  };

}
