/* Generated By:JavaCC: Do not edit this line. PMAParserConstants.java */
package javamop.logicpluginshells.javasrs.pmaparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PMAParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int EPSILON = 2;
  /** RegularExpression Id. */
  int NUMBER = 3;
  /** RegularExpression Id. */
  int MATCHES = 4;
  /** RegularExpression Id. */
  int TRUE = 5;
  /** RegularExpression Id. */
  int FALSE = 6;
  /** RegularExpression Id. */
  int COLON = 7;
  /** RegularExpression Id. */
  int OPENA = 8;
  /** RegularExpression Id. */
  int CLOSEA = 9;
  /** RegularExpression Id. */
  int OPENB = 10;
  /** RegularExpression Id. */
  int CLOSEB = 11;
  /** RegularExpression Id. */
  int FAIL = 12;
  /** RegularExpression Id. */
  int SUCCEED = 13;
  /** RegularExpression Id. */
  int BEGIN = 14;
  /** RegularExpression Id. */
  int END = 15;
  /** RegularExpression Id. */
  int PERIOD = 16;
  /** RegularExpression Id. */
  int ARROW = 17;
  /** RegularExpression Id. */
  int TERMINAL = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "\"#epsilon\"",
    "<NUMBER>",
    "\"matches\"",
    "\"true\"",
    "\"false\"",
    "\":\"",
    "\"<\"",
    "\">\"",
    "\"[\"",
    "\"]\"",
    "\"#fail\"",
    "\"#succeed\"",
    "\"^\"",
    "\"$\"",
    "\".\"",
    "\"->\"",
    "<TERMINAL>",
    "\"@\"",
  };

}
