/* Generated By:JavaCC: Do not edit this line. LTLParserConstants.java */
package logicrepository.plugins.ltl;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LTLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int LPAREN = 2;
  /** RegularExpression Id. */
  int RPAREN = 3;
  /** RegularExpression Id. */
  int NEG = 4;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int XOR = 7;
  /** RegularExpression Id. */
  int U = 8;
  /** RegularExpression Id. */
  int DU = 9;
  /** RegularExpression Id. */
  int R = 10;
  /** RegularExpression Id. */
  int S = 11;
  /** RegularExpression Id. */
  int DS = 12;
  /** RegularExpression Id. */
  int X = 13;
  /** RegularExpression Id. */
  int DX = 14;
  /** RegularExpression Id. */
  int Y = 15;
  /** RegularExpression Id. */
  int DY = 16;
  /** RegularExpression Id. */
  int ALWAYS = 17;
  /** RegularExpression Id. */
  int EVENTUALLY = 18;
  /** RegularExpression Id. */
  int EVENTUALLY_PAST = 19;
  /** RegularExpression Id. */
  int TRUE = 20;
  /** RegularExpression Id. */
  int FALSE = 21;
  /** RegularExpression Id. */
  int ATOM = 22;
  /** RegularExpression Id. */
  int DIGIT = 23;
  /** RegularExpression Id. */
  int LETTER = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "\"(\"",
    "\")\"",
    "\"not\"",
    "\"and\"",
    "\"or\"",
    "\"xor\"",
    "\"U\"",
    "\"~U\"",
    "\"R\"",
    "\"S\"",
    "\"~S\"",
    "\"o\"",
    "\"~o\"",
    "\"(*)\"",
    "\"~(*)\"",
    "\"[]\"",
    "\"<>\"",
    "\"<*>\"",
    "\"true\"",
    "\"false\"",
    "<ATOM>",
    "<DIGIT>",
    "<LETTER>",
    "\"=>\"",
    "\"<=>\"",
  };

}
