/* Generated By:JavaCC: Do not edit this line. SRSParserConstants.java */
package logicrepository.plugins.srs;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SRSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int EPSILON = 2;
  /** RegularExpression Id. */
  int FAIL = 3;
  /** RegularExpression Id. */
  int SUCCEED = 4;
  /** RegularExpression Id. */
  int BEGIN = 5;
  /** RegularExpression Id. */
  int END = 6;
  /** RegularExpression Id. */
  int PERIOD = 7;
  /** RegularExpression Id. */
  int ARROW = 8;
  /** RegularExpression Id. */
  int TERMINAL = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "\"#epsilon\"",
    "\"#fail\"",
    "\"#succeed\"",
    "\"^\"",
    "\"$\"",
    "\".\"",
    "\"->\"",
    "<TERMINAL>",
  };

}
