/* Generated By:JavaCC: Do not edit this line. AspectJParserConstants.java */
package javamop.parser.aspectj_parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AspectJParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ABSTRACT = 5;
  /** RegularExpression Id. */
  int ASSERT = 6;
  /** RegularExpression Id. */
  int BOOLEAN = 7;
  /** RegularExpression Id. */
  int BREAK = 8;
  /** RegularExpression Id. */
  int BYTE = 9;
  /** RegularExpression Id. */
  int CASE = 10;
  /** RegularExpression Id. */
  int CATCH = 11;
  /** RegularExpression Id. */
  int CHAR = 12;
  /** RegularExpression Id. */
  int CLASS = 13;
  /** RegularExpression Id. */
  int CONST = 14;
  /** RegularExpression Id. */
  int CONTINUE = 15;
  /** RegularExpression Id. */
  int _DEFAULT = 16;
  /** RegularExpression Id. */
  int DO = 17;
  /** RegularExpression Id. */
  int DOUBLE = 18;
  /** RegularExpression Id. */
  int ELSE = 19;
  /** RegularExpression Id. */
  int ENUM = 20;
  /** RegularExpression Id. */
  int EXTENDS = 21;
  /** RegularExpression Id. */
  int FALSE = 22;
  /** RegularExpression Id. */
  int FINAL = 23;
  /** RegularExpression Id. */
  int FINALLY = 24;
  /** RegularExpression Id. */
  int FLOAT = 25;
  /** RegularExpression Id. */
  int FOR = 26;
  /** RegularExpression Id. */
  int NEW = 27;
  /** RegularExpression Id. */
  int IF = 28;
  /** RegularExpression Id. */
  int IMPLEMENTS = 29;
  /** RegularExpression Id. */
  int INSTANCEOF = 30;
  /** RegularExpression Id. */
  int INT = 31;
  /** RegularExpression Id. */
  int INTERFACE = 32;
  /** RegularExpression Id. */
  int LONG = 33;
  /** RegularExpression Id. */
  int NATIVE = 34;
  /** RegularExpression Id. */
  int NULL = 35;
  /** RegularExpression Id. */
  int PACKAGE = 36;
  /** RegularExpression Id. */
  int PRIVATE = 37;
  /** RegularExpression Id. */
  int PROTECTED = 38;
  /** RegularExpression Id. */
  int PUBLIC = 39;
  /** RegularExpression Id. */
  int RETURN = 40;
  /** RegularExpression Id. */
  int SHORT = 41;
  /** RegularExpression Id. */
  int STATIC = 42;
  /** RegularExpression Id. */
  int STRICTFP = 43;
  /** RegularExpression Id. */
  int SUPER = 44;
  /** RegularExpression Id. */
  int SWITCH = 45;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 46;
  /** RegularExpression Id. */
  int THIS = 47;
  /** RegularExpression Id. */
  int THROW = 48;
  /** RegularExpression Id. */
  int THROWS = 49;
  /** RegularExpression Id. */
  int TRANSIENT = 50;
  /** RegularExpression Id. */
  int TRUE = 51;
  /** RegularExpression Id. */
  int TRY = 52;
  /** RegularExpression Id. */
  int VOID = 53;
  /** RegularExpression Id. */
  int VOLATILE = 54;
  /** RegularExpression Id. */
  int WHILE = 55;
  /** RegularExpression Id. */
  int EVENT = 56;
  /** RegularExpression Id. */
  int CREATION = 57;
  /** RegularExpression Id. */
  int UNSYNC = 58;
  /** RegularExpression Id. */
  int DECENT = 59;
  /** RegularExpression Id. */
  int PERTHREAD = 60;
  /** RegularExpression Id. */
  int SUFFIX = 61;
  /** RegularExpression Id. */
  int BEFORE = 62;
  /** RegularExpression Id. */
  int AFTER = 63;
  /** RegularExpression Id. */
  int AROUND = 64;
  /** RegularExpression Id. */
  int CALL = 65;
  /** RegularExpression Id. */
  int EXEC = 66;
  /** RegularExpression Id. */
  int GET = 67;
  /** RegularExpression Id. */
  int SET = 68;
  /** RegularExpression Id. */
  int TARGET = 69;
  /** RegularExpression Id. */
  int WITHIN = 70;
  /** RegularExpression Id. */
  int ARGS = 71;
  /** RegularExpression Id. */
  int THREAD = 72;
  /** RegularExpression Id. */
  int CONDITION = 73;
  /** RegularExpression Id. */
  int CFLOW = 74;
  /** RegularExpression Id. */
  int CFLOWBELOW = 75;
  /** RegularExpression Id. */
  int RETURNING = 76;
  /** RegularExpression Id. */
  int THROWING = 77;
  /** RegularExpression Id. */
  int ENDPROGRAM = 78;
  /** RegularExpression Id. */
  int ENDTHREAD = 79;
  /** RegularExpression Id. */
  int ENDOBJECT = 80;
  /** RegularExpression Id. */
  int STARTTHREAD = 81;
  /** RegularExpression Id. */
  int LONG_LITERAL = 82;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 83;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 84;
  /** RegularExpression Id. */
  int HEX_LITERAL = 85;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 86;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 87;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 88;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 89;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 90;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 91;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 92;
  /** RegularExpression Id. */
  int STRING_LITERAL = 93;
  /** RegularExpression Id. */
  int IDPATTERN = 94;
  /** RegularExpression Id. */
  int LETTER = 95;
  /** RegularExpression Id. */
  int PART_LETTER = 96;
  /** RegularExpression Id. */
  int LPAREN = 97;
  /** RegularExpression Id. */
  int RPAREN = 98;
  /** RegularExpression Id. */
  int LBRACE = 99;
  /** RegularExpression Id. */
  int RBRACE = 100;
  /** RegularExpression Id. */
  int LBRACKET = 101;
  /** RegularExpression Id. */
  int RBRACKET = 102;
  /** RegularExpression Id. */
  int SEMICOLON = 103;
  /** RegularExpression Id. */
  int COMMA = 104;
  /** RegularExpression Id. */
  int AT = 105;
  /** RegularExpression Id. */
  int ASSIGN = 106;
  /** RegularExpression Id. */
  int LT = 107;
  /** RegularExpression Id. */
  int BANG = 108;
  /** RegularExpression Id. */
  int TILDE = 109;
  /** RegularExpression Id. */
  int HOOK = 110;
  /** RegularExpression Id. */
  int COLON = 111;
  /** RegularExpression Id. */
  int EQ = 112;
  /** RegularExpression Id. */
  int LE = 113;
  /** RegularExpression Id. */
  int GE = 114;
  /** RegularExpression Id. */
  int NE = 115;
  /** RegularExpression Id. */
  int SC_OR = 116;
  /** RegularExpression Id. */
  int SC_AND = 117;
  /** RegularExpression Id. */
  int INCR = 118;
  /** RegularExpression Id. */
  int DECR = 119;
  /** RegularExpression Id. */
  int PLUS = 120;
  /** RegularExpression Id. */
  int MINUS = 121;
  /** RegularExpression Id. */
  int SLASH = 122;
  /** RegularExpression Id. */
  int BIT_AND = 123;
  /** RegularExpression Id. */
  int BIT_OR = 124;
  /** RegularExpression Id. */
  int XOR = 125;
  /** RegularExpression Id. */
  int REM = 126;
  /** RegularExpression Id. */
  int LSHIFT = 127;
  /** RegularExpression Id. */
  int PLUSASSIGN = 128;
  /** RegularExpression Id. */
  int MINUSASSIGN = 129;
  /** RegularExpression Id. */
  int STARASSIGN = 130;
  /** RegularExpression Id. */
  int SLASHASSIGN = 131;
  /** RegularExpression Id. */
  int ANDASSIGN = 132;
  /** RegularExpression Id. */
  int ORASSIGN = 133;
  /** RegularExpression Id. */
  int XORASSIGN = 134;
  /** RegularExpression Id. */
  int REMASSIGN = 135;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 136;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 137;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 138;
  /** RegularExpression Id. */
  int ELLIPSIS = 139;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 140;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 141;
  /** RegularExpression Id. */
  int GT = 142;
  /** RegularExpression Id. */
  int DOTDOT = 143;
  /** RegularExpression Id. */
  int DOT = 144;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"abstract\"",
    "\"assert\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"new\"",
    "\"if\"",
    "\"implements\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"event\"",
    "\"creation\"",
    "\"unsynchronized\"",
    "\"decentralized\"",
    "\"perthread\"",
    "\"suffix\"",
    "\"before\"",
    "\"after\"",
    "\"around\"",
    "\"call\"",
    "\"execution\"",
    "\"get\"",
    "\"set\"",
    "\"target\"",
    "\"within\"",
    "\"args\"",
    "\"thread\"",
    "\"condition\"",
    "\"cflow\"",
    "\"cflowbelow\"",
    "\"returning\"",
    "\"throwing\"",
    "\"endProgram\"",
    "\"endThread\"",
    "\"endObject\"",
    "\"startThread\"",
    "<LONG_LITERAL>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDPATTERN>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
    "\"..\"",
    "\".\"",
    "\"*\"",
  };

}
