//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.05 at 03:18:32 PM CST 
//


package com.runtimeverification.rvmonitor.logicrepository.parser.logicrepositorysyntax;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for LogicRepositoryType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="LogicRepositoryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Client" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Events" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Property" type="{}PropertyType" minOccurs="0"/>
 *         &lt;element name="Categories" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CreationEvents" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Message" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EnableSets" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Statistics" type="{}StatisticsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LogicRepositoryType", propOrder = {
        "specName",
        "client",
        "events",
        "property",
        "categories",
        "creationEvents",
        "message",
        "enableSets",
        "statistics"
})
public class LogicRepositoryType {

    @XmlElement(name = "SpecName")
    protected String specName;
    @XmlElement(name = "Client")
    protected String client;
    @XmlElement(name = "Events")
    protected String events;
    @XmlElement(name = "Property")
    protected PropertyType property;
    @XmlElement(name = "Categories")
    protected String categories;
    @XmlElement(name = "CreationEvents")
    protected String creationEvents;
    @XmlElement(name = "Message")
    protected List<String> message;
    @XmlElement(name = "EnableSets")
    protected String enableSets;
    @XmlElement(name = "Statistics")
    protected StatisticsType statistics;

    /**
     * Gets the value of the specName property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getSpecName() {
        return specName;
    }

    /**
     * Sets the value of the specName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSpecName(String value) {
        this.specName = value;
    }

    /**
     * Gets the value of the client property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getClient() {
        return client;
    }

    /**
     * Sets the value of the client property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setClient(String value) {
        this.client = value;
    }

    /**
     * Gets the value of the events property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getEvents() {
        return events;
    }

    /**
     * Sets the value of the events property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEvents(String value) {
        this.events = value;
    }

    /**
     * Gets the value of the property property.
     *
     * @return possible object is
     *         {@link PropertyType }
     */
    public PropertyType getProperty() {
        return property;
    }

    /**
     * Sets the value of the property property.
     *
     * @param value allowed object is
     *              {@link PropertyType }
     */
    public void setProperty(PropertyType value) {
        this.property = value;
    }

    /**
     * Gets the value of the categories property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getCategories() {
        return categories;
    }

    /**
     * Sets the value of the categories property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCategories(String value) {
        this.categories = value;
    }

    /**
     * Gets the value of the creationEvents property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getCreationEvents() {
        return creationEvents;
    }

    /**
     * Sets the value of the creationEvents property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCreationEvents(String value) {
        this.creationEvents = value;
    }

    /**
     * Gets the value of the message property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the message property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessage().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     */
    public List<String> getMessage() {
        if (message == null) {
            message = new ArrayList<String>();
        }
        return this.message;
    }

    /**
     * Gets the value of the enableSets property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getEnableSets() {
        return enableSets;
    }

    /**
     * Sets the value of the enableSets property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEnableSets(String value) {
        this.enableSets = value;
    }

    /**
     * Gets the value of the statistics property.
     *
     * @return possible object is
     *         {@link StatisticsType }
     */
    public StatisticsType getStatistics() {
        return statistics;
    }

    /**
     * Sets the value of the statistics property.
     *
     * @param value allowed object is
     *              {@link StatisticsType }
     */
    public void setStatistics(StatisticsType value) {
        this.statistics = value;
    }

}
