//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.05 at 03:18:32 PM CST 
//


package com.runtimeverification.rvmonitor.logicrepository.parser.logicrepositorysyntax;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StatisticsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StatisticsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TotalRVMCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CurrentClient" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ClientCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CurrentLogic" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LogicCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ClientAndLogicCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TotalExecutionTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatisticsType", propOrder = {
    "totalRVMCount",
    "currentClient",
    "clientCount",
    "currentLogic",
    "logicCount",
    "clientAndLogicCount",
    "totalExecutionTime"
})
public class StatisticsType {

    @XmlElement(name = "TotalRVMCount")
    protected int totalRVMCount;
    @XmlElement(name = "CurrentClient", required = true)
    protected String currentClient;
    @XmlElement(name = "ClientCount")
    protected int clientCount;
    @XmlElement(name = "CurrentLogic", required = true)
    protected String currentLogic;
    @XmlElement(name = "LogicCount")
    protected int logicCount;
    @XmlElement(name = "ClientAndLogicCount")
    protected int clientAndLogicCount;
    @XmlElement(name = "TotalExecutionTime", required = true)
    protected String totalExecutionTime;

    /**
     * Gets the value of the totalRVMCount property.
     * 
     */
    public int getTotalRVMCount() {
        return totalRVMCount;
    }

    /**
     * Sets the value of the totalRVMCount property.
     * 
     */
    public void setTotalRVMCount(int value) {
        this.totalRVMCount = value;
    }

    /**
     * Gets the value of the currentClient property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentClient() {
        return currentClient;
    }

    /**
     * Sets the value of the currentClient property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentClient(String value) {
        this.currentClient = value;
    }

    /**
     * Gets the value of the clientCount property.
     * 
     */
    public int getClientCount() {
        return clientCount;
    }

    /**
     * Sets the value of the clientCount property.
     * 
     */
    public void setClientCount(int value) {
        this.clientCount = value;
    }

    /**
     * Gets the value of the currentLogic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentLogic() {
        return currentLogic;
    }

    /**
     * Sets the value of the currentLogic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentLogic(String value) {
        this.currentLogic = value;
    }

    /**
     * Gets the value of the logicCount property.
     * 
     */
    public int getLogicCount() {
        return logicCount;
    }

    /**
     * Sets the value of the logicCount property.
     * 
     */
    public void setLogicCount(int value) {
        this.logicCount = value;
    }

    /**
     * Gets the value of the clientAndLogicCount property.
     * 
     */
    public int getClientAndLogicCount() {
        return clientAndLogicCount;
    }

    /**
     * Sets the value of the clientAndLogicCount property.
     * 
     */
    public void setClientAndLogicCount(int value) {
        this.clientAndLogicCount = value;
    }

    /**
     * Gets the value of the totalExecutionTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalExecutionTime() {
        return totalExecutionTime;
    }

    /**
     * Sets the value of the totalExecutionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalExecutionTime(String value) {
        this.totalExecutionTime = value;
    }

}
