/* Generated By:JavaCC: Do not edit this line. EREParserConstants.java */
package logicrepository.plugins.ere;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EREParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int LPAREN = 2;
  /** RegularExpression Id. */
  int RPAREN = 3;
  /** RegularExpression Id. */
  int NEG = 4;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int STAR = 7;
  /** RegularExpression Id. */
  int PLUS = 8;
  /** RegularExpression Id. */
  int EPSILON = 9;
  /** RegularExpression Id. */
  int EMPTY = 10;
  /** RegularExpression Id. */
  int SYMBOL = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;
  /** RegularExpression Id. */
  int LETTER = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "\"(\"",
    "\")\"",
    "\"~\"",
    "\"&\"",
    "\"|\"",
    "\"*\"",
    "\"+\"",
    "\"epsilon\"",
    "\"empty\"",
    "<SYMBOL>",
    "<DIGIT>",
    "<LETTER>",
  };

}
