/* Generated By:JavaCC: Do not edit this line. PTCARET_PseudoCode_ParserConstants.java */
package javamop.logicpluginshells.javaptcaret.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PTCARET_PseudoCode_ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OR = 5;
  /** RegularExpression Id. */
  int AND = 6;
  /** RegularExpression Id. */
  int XOR = 7;
  /** RegularExpression Id. */
  int NOT = 8;
  /** RegularExpression Id. */
  int CONSTANT = 9;
  /** RegularExpression Id. */
  int TRUE = 10;
  /** RegularExpression Id. */
  int FALSE = 11;
  /** RegularExpression Id. */
  int OUTPUT = 12;
  /** RegularExpression Id. */
  int ALPHA = 13;
  /** RegularExpression Id. */
  int BETA = 14;
  /** RegularExpression Id. */
  int ID = 15;
  /** RegularExpression Id. */
  int DIGIT = 16;
  /** RegularExpression Id. */
  int LETTER = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"||\"",
    "\"&&\"",
    "\"^\"",
    "\"!\"",
    "<CONSTANT>",
    "\"true\"",
    "\"false\"",
    "\"output\"",
    "\"$alpha$\"",
    "\"$beta$\"",
    "<ID>",
    "<DIGIT>",
    "<LETTER>",
    "\"(\"",
    "\")\"",
    "\":=\"",
    "\";\"",
    "\"[\"",
    "\"]\"",
  };

}
